SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_WIDTH = 325
PLAYER_HEIGHT = 25
PLAYER_START_X = 475
PLAYER_START_Y = 600
PLAYER_SPEED = 400

BALL_WIDTH = 50
BALL_HEIGHT = 50
BALL_START_X = PLAYER_START_X + 150
BALL_START_Y = PLAYER_START_Y - 100
BALL_SPEED = 200

BOUNDARY_WIDTH = 25
BOUNDARY_HEIGHT = SCREEN_HEIGHT
BOUNDARY_LEFT_X = 0
BOUNDARY_LEFT_Y = 0
BOUNDARY_RIGHT_X = SCREEN_WIDTH - BOUNDARY_WIDTH
BOUNDARY_RIGHT_Y = 0

BOUNDARY_TOP_WIDTH = SCREEN_WIDTH
BOUNDARY_TOP_HEIGHT = 25
BOUNDARY_TOP_X = 0
BOUNDARY_TOP_Y = 0

BRICK_WIDTH = 0
BRICK_HEIGHT = 0
